export const Color = [
    { name: "Red", value: "red", hex: "#FF0000" },
    { name: "Maroon", value: "maroon", hex: "#800000" },
    { name: "Crimson", value: "crimson", hex: "#DC143C" },
    { name: "Pink", value: "pink", hex: "#FFC0CB" },
    { name: "Hot Pink", value: "hotpink", hex: "#FF69B4" },
    { name: "Magenta", value: "magenta", hex: "#FF00FF" },
    { name: "Purple", value: "purple", hex: "#800080" },
    { name: "Lavender", value: "lavender", hex: "#E6E6FA" },
    { name: "Violet", value: "violet", hex: "#8F00FF" },
    { name: "Indigo", value: "indigo", hex: "#4B0082" },
    { name: "Blue", value: "blue", hex: "#0000FF" },
    { name: "Sky Blue", value: "skyblue", hex: "#87CEEB" },
    { name: "Navy", value: "navy", hex: "#000080" },
    { name: "Teal", value: "teal", hex: "#008080" },
    { name: "Cyan", value: "cyan", hex: "#00FFFF" },
    { name: "Turquoise", value: "turquoise", hex: "#40E0D0" },
    { name: "Green", value: "green", hex: "#008000" },
    { name: "Olive", value: "olive", hex: "#808000" },
    { name: "Lime", value: "lime", hex: "#00FF00" },
    { name: "Mint Green", value: "mintgreen", hex: "#98FF98" },
    { name: "Yellow", value: "yellow", hex: "#FFFF00" },
    { name: "Mustard", value: "mustard", hex: "#FFDB58" },
    { name: "Gold", value: "gold", hex: "#FFD700" },
    { name: "Orange", value: "orange", hex: "#FFA500" },
    { name: "Coral", value: "coral", hex: "#FF7F50" },
    { name: "Peach", value: "peach", hex: "#FFE5B4" },
    { name: "Brown", value: "brown", hex: "#A52A2A" },
    { name: "Beige", value: "beige", hex: "#F5F5DC" },
    { name: "Tan", value: "tan", hex: "#D2B48C" },
    { name: "Cream", value: "cream", hex: "#FFFDD0" },
    { name: "Grey", value: "grey", hex: "#808080" },
    { name: "Silver", value: "silver", hex: "#C0C0C0" },
    { name: "Black", value: "black", hex: "#000000" },
    { name: "Charcoal", value: "charcoal", hex: "#36454F" },
    { name: "White", value: "white", hex: "#FFFFFF" },
    { name: "Ivory", value: "ivory", hex: "#FFFFF0" },
    { name: "Off White", value: "offwhite", hex: "#FAF9F6" }
  ];
  